### ISSUE TITLE
Error applying you code

### ISSUE THREAD

**Issue by nikorose87** [roddehugo/patentscraper#1]
Hi
I wanted to apply your code in my research but I found the following mistake:

`    yield self.engine.open_spider(self.spider, start_requests)
exceptions.TypeError: 'module' object is not callable
2017-02-21 14:02:50 [twisted] CRITICAL: `

Do you know how to solve it?

Thanks

**Comment by roddehugo** [comment]
Hi @nikorose87,
I'm sorry but this code is old and I don't provide any support nor I will investigate any issue. 
Thanks
